repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.0.1161
    hooks:
      - id: checkov
        entry: checkov --directory .devcontainer/
        verbose: true
        args: [--framework dockerfile --soft-fail]
